In [1]:
import numpy as np
#import quaternion

print(gap(2+3))
#G = gap(ArcPresentation(PureCubicalKnot(3,1)))
#print(G.gens)
print(np.zeros((1,2)))
result = np.zeros((1,2))
result[0, 1] = 1
print(result)
result[0, 0] = 2
print(result)

r = [3, 5]
print(r)


def semi_direct_product_2(x, y, ro):
    result = [x[0] + ro(x[1])*y[0], x[1]*y[1]]
    return result 


5
[[0. 0.]]
[[0. 1.]]
[[2. 1.]]
[3, 5]


In [15]:

K.<phi> = NumberField(x^2 - x - 1)

Q.<i,j,k> = QuaternionAlgebra(K, -1, -1)
Q.variable_names()

ro_s = (1+i+j+k)/2
ro_t = (phi + i*(1/phi) + j)/2
print(ro_s^3)
print(ro_t^5)
print(ro_s*ro_t*ro_s*ro_t)
print("\n")

f_a = ro_s^-1*ro_t^-2*ro_s^-2*ro_t^-1*ro_s*ro_t^3*ro_s^2*ro_t^2*ro_s
f_b = ro_s^4*ro_t^3

m = f_a^2*f_b^2*f_a^-1*f_b^-3*f_a^-1*f_b^2
n = f_a*f_b^-2*f_a*f_b^2*f_a^-1*f_b^-1*f_a^-1*f_b^2*f_a*f_b^-2*f_a*f_b^2*f_a^-1*f_b^2
print(m)
print(n)
print(m*n*m*n)
#print("\n")

x = f_a^2*f_b^2*f_a^5*f_b^7*f_a^5
ugly = f_a^2 + f_a^2*f_b + x + x*f_b - f_b^9 - f_b^8 - f_b^7
print(ugly)

#print("\n")
#print(ugly*(1+i))

new = 1+f_a-f_a^5-f_a^5*f_b^7*f_a^5
print(new)


print("new approach\n")

cx = 1 + f_a - f_a^2*f_b^2*f_a^5 - f_a^2*f_b^2*f_a^5*f_b^7*f_a^5
print(cx)

cy = f_a^2 + f_a^2*f_b - f_a^2*f_b^2*f_a^5*f_b^9 - f_a^2*f_b^2*f_a^5*f_b^8 - f_a^2*f_b^2*f_a^5*f_b^7 - f_a^2*f_b^2*f_a^5*f_b^7*f_a^5 - f_a^2*f_b^2*f_a^5*f_b^7*f_a^5*f_b
print(cy)

print(-cy/cx)

#D = GroupSemidirectProduct(K, Q, twist=None, act_to_right=False)


-1
-1
-1
1
1
1
1/2*phi - 1 + 1/2*i + j + (1/2*phi - 1/2)*k
-1/2*phi + 1 + 1/2*i + (-phi)*j + (-1/2*phi + 1/2)*k
new approach

1 + (-phi)*j + (-phi + 1)*k
-phi + (phi + 1)*j - k
1/2*phi + 1/2 + (-1/2*phi)*i + 1/2*k


In [6]:
K.<phi> = NumberField(x^2 - x - 1)

Q.<i,j,k> = QuaternionAlgebra(K, -1, -1)
Q.variable_names()

ro_s = (1+i+j+k)/2
ro_t = (phi + i*(1/phi) + j)/2
print(ro_s^3)
print(ro_t^5)
print(ro_s*ro_t*ro_s*ro_t)
print("\n")

f_a = ro_s^-1*ro_t^-2*ro_s^-2*ro_t^-1*ro_s*ro_t^3*ro_s^2*ro_t^2*ro_s
f_b = ro_s^4*ro_t^3

m = f_a^2*f_b^2*f_a^-1*f_b^-3*f_a^-1*f_b^2
n = f_a*f_b^-2*f_a*f_b^2*f_a^-1*f_b^-1*f_a^-1*f_b^2*f_a*f_b^-2*f_a*f_b^2*f_a^-1*f_b^2
print(m)
print(n)
print(m*n*m*n)
print("\n")

c1 = f_a*f_b^8 - f_a*f_b^8*f_a*f_b^2*f_a^5*f_b^9*f_a + f_a*f_b^8*f_a*f_b^2*f_a^5*f_b^9*f_a*f_b^2*f_b^8
c2 = f_b^8*f_a + f_b^8*f_a*f_b  + f_a*f_b^8*f_a*f_b^2*f_a^5*f_b^9*f_a^5 + f_a*f_b^8*f_a*f_b^2*f_a^4*f_b + f_a*f_b^8*f_a*f_b^2*f_a^5 + f_b^9
print(c1)
print(c2)
print(-c2/c1)
print("\n")

A = matrix(K, [[2*phi -1, 2*phi, -3*phi, 3*phi +1],[ -2*phi, 2*phi -1,-3*phi -1, -3*phi], [ 3*phi, 3*phi +1, 2*phi -1, -2*phi], [-3*phi -1, 3*phi,2*phi, 2*phi -1]])
print(A)

#Compute the determinant of A
print(A.det())


-1
-1
-1


1
1
1


1/2 + 1/2*i + (-1/2)*j + (-1/2)*k
phi - 1/2 + (phi - 1/2)*i + (-phi - 1/2)*j + (phi - 1/2)*k
-phi + phi*i + phi*j + (-phi + 1)*k


[ 2*phi - 1      2*phi     -3*phi  3*phi + 1]
[    -2*phi  2*phi - 1 -3*phi - 1     -3*phi]
[     3*phi  3*phi + 1  2*phi - 1     -2*phi]
[-3*phi - 1      3*phi      2*phi  2*phi - 1]
2352*phi + 1568


In [36]:
K.<phi> = NumberField(x^2 - x - 1)

Q.<i,j,k> = QuaternionAlgebra(K, -1, -1)
Q.variable_names()

F.<a,b> = FreeGroup()
G = F / [a^2*b^2*a^-1*b^-3*a^-1*b^2, a*b^-2*a*b^2*a^-1*b^-1*a^-1*b^2*a*b^-2*a*b^2*a^-1*b^2]

h.<a,b,c> = FreeGroup()
bi = h / [(a^2)/(b^3), (c^5)/(b^3), (a*c)/(b^2) ]

#G = gap(f / [ f.1^2*f.2^2*f.1^-1*f.2^-3*f.1^-1*f.2^2, f.1*f.2^-2*f.1*f.2^2*f.1^-1*f.2^-1*f.1^-1*f.2^2*f.1*f.2^-2*f.1*f.2^2*f.1^-1*f.2^2 ])

#h = gap.FreeGroup( "a", "b", "c")
#bi = gap(h / [ (h.1^2)/(h.2^3), (h.3^5)/(h.2^3), (h.1*h.3)/(h.2^2) ])

T.<i,j,k> = QuaternionAlgebra(-1, -1)
T.variable_names()

#gap.GroupHomomorphismByImages(bi)

('i', 'j', 'k')

In [17]:
h=gap.FreeGroup( "a", "b", "c")
gap.RelatorsOfFpGroup(h) 

TypeError: Gap produced error output
Error, Variable: 'a' must have a value

   executing \$sage6:=a;;

### 1/2 surgery on 5_2 knot

In [35]:
K.<phi> = NumberField(x^2 - x - 1)

Q.<i,j,k> = QuaternionAlgebra(K, -1, -1)
Q.variable_names()

ro_s = (1+i+j+k)/2
ro_t = (phi + i*(1/phi) + j)/2

M = ro_s^-1*ro_t^-2*ro_s^-2*ro_t^-1*ro_s*ro_t^3*ro_s^2*ro_t^2*ro_s
N = ro_s^4*ro_t^3

word = [1, 1, 2, 2, 3, 4, 4, 4, 3, 2, 2]
coeff = np.zeros(3)

if word[len(word)-1] == 1:
    coeff = [1, 0, M]
if word[len(word)-1] == 2:
    coeff = [0, 1, N]
if word[len(word)-1] == 3:
    coeff = [-M^5, 0, M^5]
if word[len(word)-1] == 4:
    coeff = [0, -N^9, N^9]

#print(coeff)

def word_to_coeff(word, coeff):
    for i in range(2, len(word)+1):
        if word[len(word)-i] == 1:
            coeff[0] = 1 + M*coeff[0]
            coeff[2] = M*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 2:
            coeff[1] = 1 + N*coeff[1]
            coeff[2] = N*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 3:
            coeff[0] = 1 - M^5*coeff[0]
            coeff[2] = M^5*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 4:
            coeff[1] = 1 - N^9*coeff[1]
            coeff[2] = N^9*coeff[2]
            #print(coeff)
    return coeff

newcoeff = word_to_coeff(word, coeff)
print("Condition 1:", newcoeff)
print("Condition 1: c_1^-1*d_1 = ", coeff[0]^-1*coeff[1])
print("\n")

word = [1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 2, 2]
coeff = np.zeros(3)

if word[len(word)-1] == 1:
    coeff = [1, 0, M]
if word[len(word)-1] == 2:
    coeff = [0, 1, N]
if word[len(word)-1] == 3:
    coeff = [-M^5, 0, M^5]
if word[len(word)-1] == 4:
    coeff = [0, -N^9, N^9]

#print(coeff)

newcoeff = word_to_coeff(word, coeff)
print("Condition 2:", newcoeff)
print("Condition 2: c_2^-1*d_2 = ", coeff[0]^-1*coeff[1])
    

Condition 1: [1/2 + 1/2*phi*j + (1/2*phi - 1/2)*k, 1/2 + 1/2*phi*i + (-1/2*phi - 1/2)*j, 1]
Condition 1: c_1^-1*d_1 =  -1/2*phi + (-1/2*phi - 1/2)*j + 1/2*k


Condition 2: [1/2 + 1/2*phi*j + (1/2*phi - 1/2)*k, -2*phi + 1 - i + phi*j, 1]
Condition 2: c_2^-1*d_2 =  -1/2*phi + 1 + (3/2*phi + 1/2)*j + (-phi + 3/2)*k


### 1/7 surgery on 5_2 knot

In [29]:
K.<phi> = NumberField(x^2 - x - 1)

Q.<i,j,k> = QuaternionAlgebra(K, -1, -1)
Q.variable_names()

ro_s = (1+i+j+k)/2
ro_t = (phi + i*(1/phi) + j)/2

M = ro_s^-1*ro_t^-2*ro_s^-2*ro_t^-1*ro_s*ro_t^3*ro_s^2*ro_t^2*ro_s
N = ro_s^4*ro_t^3

word = [1, 1, 2, 2, 3, 4, 4, 4, 3, 2, 2]
coeff = np.zeros(3)

if word[len(word)-1] == 1:
    coeff = [1, 0, M]
if word[len(word)-1] == 2:
    coeff = [0, 1, N]
if word[len(word)-1] == 3:
    coeff = [-M^5, 0, M^5]
if word[len(word)-1] == 4:
    coeff = [0, -N^9, N^9]

#print(coeff)

def word_to_coeff(word, coeff):
    for i in range(2, len(word)+1):
        if word[len(word)-i] == 1:
            coeff[0] = 1 + M*coeff[0]
            coeff[2] = M*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 2:
            coeff[1] = 1 + N*coeff[1]
            coeff[2] = N*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 3:
            coeff[0] = 1 - M^5*coeff[0]
            coeff[2] = M^5*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 4:
            coeff[1] = 1 - N^9*coeff[1]
            coeff[2] = N^9*coeff[2]
            #print(coeff)
    return coeff

newcoeff = word_to_coeff(word, coeff)
print("Condition 1:", newcoeff)
print("Condition 1: c_1^-1*d_1 = ", coeff[0]^-1*coeff[1])
print("\n")


word = [1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 2, 2, 1, 2, 2, 3, 4, 3, 2, 2]
coeff = np.zeros(3)

if word[len(word)-1] == 1:
    coeff = [1, 0, M]
if word[len(word)-1] == 2:
    coeff = [0, 1, N]
if word[len(word)-1] == 3:
    coeff = [-M^5, 0, M^5]
if word[len(word)-1] == 4:
    coeff = [0, -N^9, N^9]

#print(coeff)

newcoeff = word_to_coeff(word, coeff)
print("Condition 2:", newcoeff)
print("Condition2: c_2^-1*d_2 = ", coeff[0]^-1*coeff[1])
    

Condition 1: [1/2 + 1/2*phi*j + (1/2*phi - 1/2)*k, 1/2 + 1/2*phi*i + (-1/2*phi - 1/2)*j, 1]
Condition 1: c_1^-1*d_1 =  -1/2*phi + (-1/2*phi - 1/2)*j + 1/2*k


Condition 2: [-2 + 3*phi*j + (3*phi - 3)*k, -5/2*phi + 1/2 + (phi - 3/2)*i + (1/2*phi - 1)*j, 1/2*phi + (1/2*phi - 1/2)*i + (-1/2)*j]
Condition2: c_2^-1*d_2 =  7/62*phi + 1/62 + (-5/31*phi + 15/62)*i + (19/62*phi + 2/31)*j + (-3/31*phi + 12/31)*k


### 1/12 surgery on 5_2 knot

In [34]:
K.<phi> = NumberField(x^2 - x - 1)

Q.<i,j,k> = QuaternionAlgebra(K, -1, -1)
Q.variable_names()

ro_s = (1+i+j+k)/2
ro_t = (phi + i*(1/phi) + j)/2

M = ro_s^-1*ro_t^-2*ro_s^-2*ro_t^-1*ro_s*ro_t^3*ro_s^2*ro_t^2*ro_s
N = ro_s^4*ro_t^3

word = [1, 1, 2, 2, 3, 4, 4, 4, 3, 2, 2]
coeff = np.zeros(3)

if word[len(word)-1] == 1:
    coeff = [1, 0, M]
if word[len(word)-1] == 2:
    coeff = [0, 1, N]
if word[len(word)-1] == 3:
    coeff = [-M^5, 0, M^5]
if word[len(word)-1] == 4:
    coeff = [0, -N^9, N^9]

#print(coeff)

def word_to_coeff(word, coeff):
    for i in range(2, len(word)+1):
        if word[len(word)-i] == 1:
            coeff[0] = 1 + M*coeff[0]
            coeff[2] = M*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 2:
            coeff[1] = 1 + N*coeff[1]
            coeff[2] = N*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 3:
            coeff[0] = 1 - M^5*coeff[0]
            coeff[2] = M^5*coeff[2]
            #print(coeff)
        if word[len(word)-i] == 4:
            coeff[1] = 1 - N^9*coeff[1]
            coeff[2] = N^9*coeff[2]
            #print(coeff)
    return coeff

newcoeff = word_to_coeff(word, coeff)
print("Condition 1: ", newcoeff)
print("Condition 1: c_1^-1*d_1 = ", coeff[0]^-1*coeff[1])
print("\n")


word = [1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 2, 2, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 4, 4, 1, 2, 2, 3, 4, 3, 2, 2, 1, 2, 2, 1, 2, 2, 3, 4, 3, 2, 2]
coeff = np.zeros(3)

if word[len(word)-1] == 1:
    coeff = [1, 0, M]
if word[len(word)-1] == 2:
    coeff = [0, 1, N]
if word[len(word)-1] == 3:
    coeff = [-M^5, 0, M^5]
if word[len(word)-1] == 4:
    coeff = [0, -N^9, N^9]

#print(coeff)

newcoeff = word_to_coeff(word, coeff)
print("Condition 2: ", newcoeff)
print("Condition 2: c_2^-1*d_2 = ", coeff[0]^-1*coeff[1])
    

Condition 1:  [1/2 + 1/2*phi*j + (1/2*phi - 1/2)*k, 1/2 + 1/2*phi*i + (-1/2*phi - 1/2)*j, 1]
Condition 1: c_1^-1*d_1 =  -1/2*phi + (-1/2*phi - 1/2)*j + 1/2*k


Condition 2:  [-9/2 + 11/2*phi*j + (11/2*phi - 11/2)*k, -2*phi - 1/2 + (1/2*phi - 2)*i + (3/2*phi - 1/2)*j, 1/2*phi - 1/2 + 1/2*i + (-1/2*phi)*j]
Condition 2: c_2^-1*d_2 =  29/222*phi + 7/74 + (-5/111*phi + 20/111)*i + (6/37*phi - 1/222)*j + (-11/222*phi + 11/111)*k
