In [1]:
import numpy as np
#import quaternion

print(gap(2+3))
#G = gap(ArcPresentation(PureCubicalKnot(3,1)))
#print(G.gens)
print(np.zeros((1,2)))
result = np.zeros((1,2))
result[0, 1] = 1
print(result)
result[0, 0] = 2
print(result)

r = [3, 5]
print(r)


def semi_direct_product_2(x, y, ro):
    result = [x[0] + ro(x[1])*y[0], x[1]*y[1]]
    return result 


5
[[0. 0.]]
[[0. 1.]]
[[2. 1.]]
[3, 5]


In [1]:

K.<phi> = NumberField(x^2 - x - 1)

Q.<i,j,k> = QuaternionAlgebra(K, -1, -1)
Q.variable_names()

ro_s = (1+i+j+k)/2
ro_t = (phi + i*(1/phi) + j)/2
print(ro_s^3)
print(ro_t^5)
print(ro_s*ro_t*ro_s*ro_t)
#print("\n")

f_a = ro_s^-1*ro_t^-2*ro_s^-2*ro_t^-1*ro_s*ro_t^3*ro_s^2*ro_t^2*ro_s
f_b = ro_s^4*ro_t^3

m = f_a^2*f_b^2*f_a^-1*f_b^-3*f_a^-1*f_b^2
n = f_a*f_b^-2*f_a*f_b^2*f_a^-1*f_b^-1*f_a^-1*f_b^2*f_a*f_b^-2*f_a*f_b^2*f_a^-1*f_b^2
print(m)
print(n)
print(m*n*m*n)
#print("\n")

x = f_a^2*f_b^2*f_a^5*f_b^7*f_a^5
ugly = f_a^2 + f_a^2*f_b + x + x*f_b - f_b^9 - f_b^8 - f_b^7
print(ugly)

#print("\n")
#print(ugly*(1+i))

new = 1+f_a-f_a^5-f_a^5*f_b^7*f_a^5
print(new)


print("new approach\n")

cx = 1 + f_a - f_a^2*f_b^2*f_a^5 - f_a^2*f_b^2*f_a^5*f_b^7*f_a^5
print(cx)

cy = f_a^2 + f_a^2*f_b - f_a^2*f_b^2*f_a^5*f_b^9 - f_a^2*f_b^2*f_a^5*f_b^8 - f_a^2*f_b^2*f_a^5*f_b^7 - f_a^2*f_b^2*f_a^5*f_b^7*f_a^5 - f_a^2*f_b^2*f_a^5*f_b^7*f_a^5*f_b
print(cy)

print(-cy/cx)

#D = GroupSemidirectProduct(K, Q, twist=None, act_to_right=False)


-1
-1
-1
1
1
1
1/2*phi - 1 + 1/2*i + j + (1/2*phi - 1/2)*k
-1/2*phi + 1 + 1/2*i + (-phi)*j + (-1/2*phi + 1/2)*k
new approach

1 + (-phi)*j + (-phi + 1)*k
-phi + (phi + 1)*j - k
1/2*phi + 1/2 + (-1/2*phi)*i + 1/2*k


In [9]:
K.<phi> = NumberField(x^2 - x - 1)

Q.<i,j,k> = QuaternionAlgebra(K, -1, -1)
Q.variable_names()

F.<a,b> = FreeGroup()
G = F / [a^2*b^2*a^-1*b^-3*a^-1*b^2, a*b^-2*a*b^2*a^-1*b^-1*a^-1*b^2*a*b^-2*a*b^2*a^-1*b^2]

h.<a,b,c> = FreeGroup()
bi = h / [(a^2)/(b^3), (c^5)/(b^3), (a*c)/(b^2) ]

f=gap.FreeGroup( "a", "b")
#G = gap(f / [ f.1^2*f.2^2*f.1^-1*f.2^-3*f.1^-1*f.2^2, f.1*f.2^-2*f.1*f.2^2*f.1^-1*f.2^-1*f.1^-1*f.2^2*f.1*f.2^-2*f.1*f.2^2*f.1^-1*f.2^2 ])

#h = gap.FreeGroup( "a", "b", "c")
#bi = gap(h / [ (h.1^2)/(h.2^3), (h.3^5)/(h.2^3), (h.1*h.3)/(h.2^2) ])

T.<i,j,k> = QuaternionAlgebra(-1, -1)
T.variable_names()

#gap.GroupHomomorphismByImages(bi)

TypeError: gap() takes exactly one argument (2 given)

In [11]:
h=gap.FreeGroup( "a", "b", "c")
gap.RelatorsOfFpGroup(h) 

TypeError: Gap produced error output
Error, Variable: 'a' must have a value

   executing \$sage3:=a;;